name: List Directory
description: Get a list of folders from a given input source directory as a JSON array.

inputs:
  source:
    required: true
    type: string
outputs:
  directories:
    value: ${{ steps.list-dir.outputs.directories }}

runs:
  using: composite

  steps:
    - name: Get List of Directories
      id: list-dir
      shell: bash
      run: |
        cd ${{ inputs.source }}
        array=(*/)
        directories="$(jq -c -n '$ARGS.positional' --args "${array[@]}")"
        echo $directories
        echo "directories=$directories" >> $GITHUB_OUTPUT
