
name: Build Image and Publish to GCR

on:
     workflow_dispatch :
    # workflow_call:
         inputs:
            environment:
                type: string
                required: true
    #        branch:
    #             type: string
    #             required: true      

#on:
#  push:
#    branches: [ "Main-Prod" ]

env:
    DOCKER_IMAGE: sts-knowledgebase
    ACR_DOCKER_IMAGE: sts-knowledgebase
    ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
    ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}

jobs:

    build-image:
        name: Build & Publish Image
        runs-on: ubuntu-22.04

        environment: ${{ inputs.environment }}  
        
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                ref: ${{ github.ref }}

            - name: Get GitHub Runner IP
              id: whats-my-ip
              uses: ./.github/actions/whats-my-ip-address


            - name: GitHub Container Registry Login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

                                 
            - name: Bump version and push tag
              uses: mathieudutour/github-tag-action@v6.1
              id: tag_version
              with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create a GitHub release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.tag_version.outputs.new_tag }}
                name: Release ${{ steps.tag_version.outputs.new_tag }}
                body: ${{ steps.tag_version.outputs.changelog }}    

            - name: Build Image & Publish To GCR
              uses: docker/build-push-action@v4
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: docker.pkg.github.com
                context: ./
                file: ./src/App/Dockerfile
                build-args: COMMIT_SHA=${{ inputs.checked-out-sha }}
                #run: |
                #    docker build . --tag ghcr.io/dfe-digital/sts-knowledgebase/App:latest
                #    docker push ghcr.io/dfe-digital/sts-knowledgebase/App:latest
                tags: |
                    ghcr.io/dfe-digital/${{ env.DOCKER_IMAGE}}:${{ steps.tag_version.outputs.new_tag }}
                push: true

            #- name: Set Action Secret
            #  uses: action-pack/increment@v2
            #  with:
            #    name: 'PATCH_VERSION'
            #    token: ${{ secrets.REPO_ACCESS_TOKEN }}   

            - name: Login with AZ
              uses: ./.github/actions/azure-login
              with:
                az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
                az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
                az_client_id: ${{ secrets.AZ_CLIENT_ID }}
                az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}

            - name: Pull Image From GCR
              run: docker pull ghcr.io/dfe-digital/${{ env.DOCKER_IMAGE}}:${{ steps.tag_version.outputs.new_tag }}


            - name: Azure Container Registry Login
              uses: docker/login-action@v3
              with:
                registry: ${{ secrets.AZ_ACR_URL }}
                username: ${{ secrets.AZ_CLIENT_ID }}
                password: ${{ secrets.AZ_CLIENT_SECRET }}
            
            - name: Push Image To ACR
              run: |
                docker tag ghcr.io/dfe-digital/${{ env.DOCKER_IMAGE}}:${{ steps.tag_version.outputs.new_tag }} ${{ secrets.AZ_ACR_URL }}/${{ env.ACR_DOCKER_IMAGE }}::${{ steps.tag_version.outputs.new_tag }}
                docker push ${{ secrets.AZ_ACR_URL }}/${{ env.ACR_DOCKER_IMAGE }}:${{ steps.tag_version.outputs.new_tag }}