name: Code PR Check

on:
  push:
    branches: ["main", "Development"]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: ["main", "Development"]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/code-pr-check.yml"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-test-web-app:
    name: Build and run unit tests
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Install dotnet coverage
      run: dotnet tool install --global dotnet-coverage --version 17.9.3
