name: Deploy Image to Environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      branch:
        type: string
        required: true
      checked-out-sha:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: true

env:
  GCR_DOCKER_IMAGE: sts-content-and-support
  ACR_DOCKER_IMAGE: content-support-app
  GITHUB_CONTAINER_REGISTRY: ghcr.io
  ORG_NAME: dfe-digital

jobs:
  pull-image-from-gcr-and-publish-to-acr:
    runs-on: ubuntu-22.04
    name: Pull Image From GitHub Container Registry and Publish to Azure Container Registry
    environment: ${{ inputs.environment }}

    steps:
      - name: GitHub Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image From GCR
        run: docker pull ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.GCR_DOCKER_IMAGE }}:${{ inputs.branch }}-${{ inputs.checked-out-sha }}

      - name: Azure Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZ_ACR_URL }}
          username: ${{ secrets.AZ_CLIENT_ID }}
          password: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: Push Image To ACR
        run: |
          docker tag ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.GCR_DOCKER_IMAGE }}:${{ inputs.branch }}-${{ inputs.checked-out-sha }} ${{ secrets.AZ_ACR_URL }}/${{ env.ACR_DOCKER_IMAGE }}:${{ inputs.branch }}-${{ inputs.checked-out-sha }}-${{ inputs.environment }}
          docker push ${{ secrets.AZ_ACR_URL }}/${{ env.ACR_DOCKER_IMAGE }}:${{ inputs.branch }}-${{ inputs.checked-out-sha }}-${{ inputs.environment }}

  deploy-image:
    runs-on: ubuntu-22.04
    name: Deploy Image To ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    needs: [pull-image-from-gcr-and-publish-to-acr]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}
          az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: Update Azure Container Apps Revision
        uses: azure/CLI@v1
        id: azure
        with:
          azcliversion: 2.61.0
          inlineScript: |
            az containerapp update \
              --name ${{ secrets.AZ_ACA_NAME }} \
              --environment main \
              --resource-group ${{ secrets.AZ_ACA_RESOURCE_GROUP }} \
              --image ${{ secrets.AZ_ACR_URL }}/${{ env.ACR_DOCKER_IMAGE }}:${{ inputs.branch }}-${{ inputs.checked-out-sha }}-${{ inputs.environment }} \
